In [1]:
import pickle
import numpy as np

In [2]:
## Code to load the array
with open('array.pickle', 'rb') as p:
    arr = pickle.load(p)

Check that the size of the array (arr) is 1000. Please report if any discrepancy.

## Task 1: Resize the array to a (20x50) matrix

In [5]:
## BEGIN CODE
arr=arr.reshape(20,50)
print(arr.shape)
## END CODE

(20, 50)


## Task 2: Find the transpose of this matrix

In [7]:
## BEGIN CODE
a=arr.T
print(a.shape)
## END CODE

(50, 20)


## Task 3: Find the dot product of the matrices created in Tasks 1 & 2

In [10]:
## BEGIN CODE
m=np.dot(arr,a)
print(m.shape)
## END CODE

(20, 20)


## Task 4: Find the row-wise sum of the resulting matrix

In [11]:
## BEGIN CODE
np.sum(m,axis=1)
## END CODE

array([2365442.27809957, 3002112.3995789 , 2779184.43777157,
       2477210.32440039, 2627759.87742664, 2220803.79590608,
       2429710.18283941, 2508044.22721641, 2459318.36600334,
       2325031.07739166, 2896081.10050922, 2762062.07921721,
       2660473.74582437, 2141287.18395127, 2694809.41626161,
       2254508.32241154, 2480788.07237605, 2727792.51946167,
       2586794.20382212, 2681242.33967484])

## Task 5: Find the square root of all elements in the resulting matrix

In [12]:
## BEGIN CODE
np.sqrt(m)
## END CODE

array([[383.20884233, 368.04955471, 366.7261367 , 335.65330645,
        337.14869887, 306.12173484, 348.5346524 , 325.75448559,
        329.35460312, 313.00331821, 363.12453706, 350.66770704,
        343.12687274, 320.148032  , 365.46226849, 334.57811689,
        334.30769974, 356.21945695, 337.73396525, 348.25631728],
       [368.04955471, 460.0024396 , 397.05539051, 377.20237834,
        387.9302227 , 359.68491431, 384.36051272, 374.26585254,
        371.70559781, 366.43674522, 416.18706825, 397.47259819,
        387.42302296, 350.81534175, 395.49547099, 355.3684654 ,
        384.91045813, 417.47902002, 388.21341093, 393.42228206],
       [366.7261367 , 397.05539051, 445.26520526, 374.29163259,
        364.77593293, 331.31140457, 364.82317191, 364.40334362,
        358.90077213, 346.87540344, 397.35395057, 368.61264245,
        389.74709123, 344.82884133, 376.39728353, 343.07571458,
        360.13378866, 388.54818747, 378.35382969, 378.24938383],
       [335.65330645, 377.20237834, 3

## Task 6: Find the sine value of all elements in the resulting matrix

In [14]:
## BEGIN CODE
np.sin(m)
## END CODE

array([[-9.99812508e-01,  9.58782809e-01,  3.71447112e-01,
        -6.08057276e-01,  1.39301003e-01,  5.07004885e-02,
        -4.26651890e-01, -6.68189992e-01,  9.99626239e-01,
        -4.88447958e-01,  4.81668025e-01, -3.69888415e-01,
         9.88209546e-01, -2.97495470e-01,  8.41262202e-01,
         9.59962483e-01,  4.97356656e-01, -2.30544066e-01,
        -6.55455922e-01, -9.57478673e-01],
       [ 9.58782809e-01, -2.67943181e-01,  9.99952030e-01,
        -8.89869693e-01,  9.59829930e-01,  6.36138269e-01,
         3.80928133e-01, -6.71873084e-01, -8.12326148e-01,
        -8.80367612e-01,  3.51678053e-02,  5.49229898e-02,
        -6.64263738e-01,  4.69031564e-01,  8.89412237e-02,
         8.44007712e-01, -9.92563075e-01, -5.18485552e-01,
         9.20613308e-01,  8.93539497e-01],
       [ 3.71447112e-01,  9.99952030e-01,  9.95302384e-01,
        -9.26509787e-01,  6.25362264e-01, -5.19821870e-04,
        -6.94408390e-01,  8.18366441e-01, -9.69663111e-01,
        -4.37772130e-01, -1.5

## Create submission file

In [15]:
## Assign the name of the variable containing the final matrix to VARIABLE_NAME variable.

VARIABLE_NAME = m
with open('submission.pickle', 'wb') as p:
    pickle.dump(VARIABLE_NAME, p)